Fix: lighthouse ci #80

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -24,11 +24,11 @@ jobs:
         run: |
           npm run build
 
-      - name: Run Lighthouse CI
-        env:
-          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-        run: |
-          lhci autorun || echo "Fail to Run Lighthouse CI!"
+      # - name: Run Lighthouse CI
+      #   env:
+      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+      #   run: |
+      #     lhci autorun || echo "Fail to Run Lighthouse CI!"
 
       - name: Audit URLs using Lighthouse
         uses: treosh/lighthouse-ci-action@v11
